import i18n from 'i18next';

import {
  WeatherBg1,
  WeatherBg10,
  WeatherBg11,
  WeatherBg12,
  WeatherBg13,
  WeatherBg2,
  WeatherBg3,
  WeatherBg4,
  WeatherBg5,
  WeatherBg6,
  WeatherBg7,
  WeatherBg8,
  WeatherBg9,
  WeatherIcon10,
  WeatherIcon11,
  WeatherIcon12,
  WeatherIcon13,
  WeatherIcon2,
  WeatherIcon3,
  WeatherIcon4,
  WeatherIcon5,
  WeatherIcon6,
  WeatherIcon7,
  WeatherIcon8,
  WeatherIcon9,
} from '../../assets/assets';

export const weatherIndicatorImage = [
  {
    type: 0,
    name: '-',
    background: WeatherBg5,
    icon: WeatherIcon5,
  },
  {
    type: 1,
    name: i18n.t('weatherPartlyCloudy'),
    background: WeatherBg1,
    icon: WeatherIcon2,
  },
  {
    type: 2,
    name: i18n.t('weatherCloudy'),
    background: WeatherBg2,
    icon: WeatherIcon2,
  },
  {
    type: 3,
    name: i18n.t('weatherPartlyCloudyRain'),
    background: WeatherBg3,
    icon: WeatherIcon3,
  },
  {
    type: 4,
    name: i18n.t('weatherSnow'),
    background: WeatherBg4,
    icon: WeatherIcon4,
  },
  {
    type: 5,
    name: i18n.t('weatherSunny'),
    background: WeatherBg5,
    icon: WeatherIcon5,
  },
  {
    type: 6,
    name: i18n.t('weatherCloudyRainPartialThunder'),
    background: WeatherBg6,
    icon: WeatherIcon6,
  },
  {
    type: 7,
    name: i18n.t('weatherOvercast'),
    background: WeatherBg7,
    icon: WeatherIcon7,
  },
  {
    type: 8,
    name: i18n.t('weatherMist'),
    background: WeatherBg8,
    icon: WeatherIcon8,
  },
  {
    type: 9,
    name: i18n.t('weatherOvercastRain'),
    background: WeatherBg9,
    icon: WeatherIcon9,
  },
  {
    type: 10,
    name: i18n.t('weatherCloudyRain'),
    background: WeatherBg10,
    icon: WeatherIcon10,
  },
  {
    type: 11,
    name: i18n.t('weatherMostCloudyRainPartialThunder'),
    background: WeatherBg11,
    icon: WeatherIcon11,
  },
  {
    type: 12,
    name: i18n.t('weatherPartialCloudRainThunder'),
    background: WeatherBg12,
    icon: WeatherIcon12,
  },
  {
    type: 13,
    name: i18n.t('weatherFog'),
    background: WeatherBg13,
    icon: WeatherIcon13,
  },
];
